---
title: "R Notebook"
output: html_notebook
---

```{r}
library(MASS);
library(clValid);
library(mixture);
library(MixGHD);
library(teigen);
library(mixsmsn);
library(meanShiftR);
```


```{r}
#parameters
mu1 <- c(0,0)
mu<- list(c(2.5,2.5),c(1,1),c(.5,0))
ss<- list(diag(c(1,1)),matrix(c(1,.75,.75,1),2),matrix(c(1,-.75,-.75,1),2),matrix(c(4,4.5,4.5,9),2),matrix(c(4,-4.5,-4.5,9),2) )
skew<- list(c(0,0),c(1,-1),c(1,1))  


#results matrix
param_mat<-matrix(0,nrow = 675, ncol = 17) 
colnames(param_mat)<-c('G1_mu_x1','G1_mu_x2','G2_mu_x1','G2_mu2_x2','dist_between_means','G1_var_x1','G1_var_x2','G1_covar','G1_corr','G2_var_x1','G2_var_x2','G2_covar','G2_corr','G1_skew_x1','G1_skew_x2','G2_skew_x1','G2_skew_x2')

i=0
for(mu2 in mu){
  for(s1 in ss){
    for(s2 in ss){
      for(skew1 in skew){
        for (skew2 in skew){
            i=i+1
            param_mat[i,3]<-mu2[1]
            param_mat[i,4]<-mu2[2]
            param_mat[i,5]<-sqrt( sum((mu1-mu2)^2)        )
            param_mat[i,6]<-s1[1,1]
            param_mat[i,7]<-s1[2,2]
            param_mat[i,8]<-s1[1,2]
            param_mat[i,9]<-s1[1,2]/(sqrt(s1[1,1]*s1[2,2]))
            param_mat[i,10]<-s2[1,1]
            param_mat[i,11]<-s2[2,2]
            param_mat[i,12]<-s2[1,2]
            param_mat[i,13]<-s2[1,2]/(sqrt(s2[1,1]*s2[2,2]))
            param_mat[i,14]<-skew1[1]
            param_mat[i,15]<-skew1[2]
            param_mat[i,16]<-skew2[1]
            param_mat[i,17]<-skew2[2]
            
              
        }
      }
    }
  }
}

write.csv(param_mat,'parameter_matrix.csv', row.names = FALSE)

```









